-- سفر‌دوست: Supabase schema (free plan)
create table if not exists public.profiles (
 id uuid primary key references auth.users(id) on delete cascade,
 name text not null,
 city text not null,
 country text not null,
 languages text,
 bio text,
 home text,
 avatar_url text,
 role text default 'both' check (role in ('host','traveler','both')),
 created_at timestamptz default now()
);

-- اطلاعات تماس خصوصی است و نباید در پروفایل عمومی نگهداری شود.
create table if not exists public.private_contacts (
 id uuid primary key references public.profiles(id) on delete cascade,
 phone text,
 contact_info text,
 created_at timestamptz default now(),
 updated_at timestamptz default now(),
 constraint at_least_one_contact check (
   nullif(trim(coalesce(phone,'')),'') is not null
   or nullif(trim(coalesce(contact_info,'')),'') is not null
 )
);

create table if not exists public.friend_requests (
 id bigint generated by default as identity primary key,
 sender uuid references public.profiles(id) on delete cascade,
 receiver uuid references public.profiles(id) on delete cascade,
 status text default 'pending' check(status in ('pending','accepted','declined','blocked')),
 created_at timestamptz default now(),
 unique(sender,receiver)
);

create table if not exists public.messages (
 id bigint generated by default as identity primary key,
 sender uuid references public.profiles(id) on delete cascade,
 receiver uuid references public.profiles(id) on delete cascade,
 body text not null,
 created_at timestamptz default now()
);

alter table public.profiles enable row level security;
alter table public.private_contacts enable row level security;
alter table public.friend_requests enable row level security;
alter table public.messages enable row level security;

create policy "profiles public read" on public.profiles for select using (true);
create policy "profile owner insert" on public.profiles for insert with check (auth.uid()=id);
create policy "profile owner update" on public.profiles for update using (auth.uid()=id);

create policy "private contacts owner read" on public.private_contacts for select using (auth.uid()=id);
create policy "private contacts owner insert" on public.private_contacts for insert with check (auth.uid()=id);
create policy "private contacts owner update" on public.private_contacts for update using (auth.uid()=id);
create policy "private contacts owner delete" on public.private_contacts for delete using (auth.uid()=id);

create policy "requests participants" on public.friend_requests for select using (auth.uid()=sender or auth.uid()=receiver);
create policy "send own request" on public.friend_requests for insert with check (auth.uid()=sender);
create policy "update received request" on public.friend_requests for update using (auth.uid()=receiver);

create policy "messages participants" on public.messages for select using (auth.uid()=sender or auth.uid()=receiver);
create policy "send own message" on public.messages for insert with check (auth.uid()=sender);
